[package]
name = "randbot"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "randbot"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
router-lib = { path = "../../lib/router-lib/", version = "0.0.1" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
spl-associated-token-account = "1.0.5"
shellexpand = "3.1.0"
solana-account-decoder = "1.17"

reqwest = { workspace = true, features = ["json"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
atty = "0.2.14"
toml = "0.5.11"
rand = "0.7.3"