app = "router-indexer"
primary_region = "nrt"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  dockerfile = 'bin/indexer/Dockerfile'

[experimental]
  cmd = ["indexer", "/usr/local/bin/template-config.toml"]

[[restart]]
  policy = "always"
  retries = 10
