[package]
name = "comparer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-channel = "1.6"
bs58 = "0.3.1"
bytemuck = "^1.7.2"
bytes = "1.0"
chrono = "0.4"
futures = "0.3.17"
futures-core = "0.3"
futures-util = "0.3"
itertools = "0.12"
jemallocator = "0.5"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ws", "http", "tls"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.10.6"
shellexpand = "2.1.0"
solana-account-decoder = "1.17"
solana-client = { workspace = true }
solana-logger = "1.17"
solana-program = "1.17"
solana-program-test = "1.17"
solana-sdk = { workspace = true }
solana-transaction-status = { version = "1.17" }
spl-token = { version = "^3.0.0", features = ["no-entrypoint"] }
tokio = { workspace = true }
tokio-stream = { version = "0.1"}
tokio-tungstenite = "0.21"
toml = "0.5"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1.9.5"
indexmap = "2.0.0"
spl-associated-token-account = "1.0.5"
yellowstone-grpc-proto = { workspace = true }
lz4 = "1.24.0"
autobahn-executor = { path = "../../programs/autobahn-executor" }
router-feed-lib = { path = "../../lib/router-feed-lib" }
router-config-lib = { path = "../../lib/router-config-lib" }
router-lib = { path = "../../lib/router-lib/", version = "0.0.1" }
base64 = "0.21.7"
bincode = "1.3.3"
services-mango-lib = { git = "https://github.com/blockworks-foundation/mango-v4.git" }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tokio-postgres-rustls = "0.9.0"
postgres_query = { git = "https://github.com/nolanderc/rust-postgres-query", rev = "b4422051c8a31fbba4a35f88004c1cefb1878dd5" }
postgres-types = { version = "0.2", features = ["array-impls", "derive", "with-chrono-0_4"] }
postgres-native-tls = "0.5"
rand = "0.7.3"

[dev-dependencies]
test-case = "*"

[build-dependencies]
anyhow = { workspace = true }
vergen-gitcl = { version = "1.0.0-beta.2", features = [] }